name: creador por mi
on: 
  workflow_dispatch
jobs:
  firstone:
    runs-on: ubuntu-latest
    steps: 
      - name: descargar repo
        uses: actions/checkout@v4
      - name: listar contenido
        run: ls 