name: creador por mi
on: 
  workflow_dispatch
jobs:
  firstone:
    runs-on: ubuntu-latest
    steps: 
      - name: descargar repo
        uses: actions/checkout@v4
      - name: listar contenido
        run: ls 
  secondone:
    runs-on: ubuntu-latest
    needs: firstone
    steps:
      - uses: actions/checkout@v4
      - name: ver contenido
        run: cat archivo1.txt
  thirdone:
    env:
      VAR1: yo
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: subir contenido
        run: echo $VAR1 >> archivo1.txt
