name: nombre para mi prueba

on: workflow_dispatch

jobs:
  primero:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: echo	"FOO=bar" >> $GITHUB_ENV
      - name: Mostrar variable
        run: echo $GITHUB_ENV
