name: nombre para mi prueba

on: workflow_dispatch

jobs:
  primero:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: echo "Set variable MyVariable to true" >> $DEBUG_MESSAGE