name: CI/CD pipeline
on: 
  push:
    branches: [main,develop]
  pull_request:
    branch: main
  schedule:
    - cron: "0 2 * * 1" #Todos los Lunes 2am
jobs:
  correr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: muestrame
        run: echo "evento desencadenado {{ github.event_name }}"
      - name: mensaje
        run: echo "deberia esto funcionar ?"
