name: primero
on: 
  workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: mostrar mensaje
        run: echo "Hola mundo"
