name: primero
on: 
  workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-latest # idk 
    steps:
      - name: yo no puse esto
        uses: actions/checkout@v4
      - name: mostrar mensaje
        run: echo "Hola mundo"
