name: workflow trasladando input
on: workflow_dispatch
jobs:
  contenedor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print event type
        run: echo "el nombre del evento es ${{ github.event_name }}"
      - uses: ./.github/actions
        with:
          MY_NAME: "DLLACSA"